const tourStopsData = [
  // {
  //   title: "Museo del Novecento",
  //   image: require("@/assets/images/novecento.jpg"),
  //   caption: "Museum of Modern and Contemporary Art",
  //   price: "€5-€10",
  //   address: "Marconi Street, 1, 20122 Milano MI",
  //   rating: "4.6",
  //   label: "MUSEO",
  //   labelImage: require("../../assets/images/labelMuseum.png"),
  // },
  // {
  //   title: "Museo Poldi Pezzoli",
  //   minutes: "8 min",
  //   image: require("@/assets/images/poldi.jpg"),
  //   caption: "Museum of Ancient and Renaissance Art",
  //   price: "€10",
  //   address: "Alessandro Manzoni Street, 12, 20121 Milan MI",
  //   rating: "4.7",
  //   label: "MUSEO",
  //   labelImage: require("../../assets/images/labelMuseum.png"),
  // },
  // {
  //   title: "Monument to Giuseppe Missori",
  //   minutes: "11 min",
  //   image: require("@/assets/images/missori.jpg"),
  //   caption: "Statua equestre in onore del patriota italiano Giuseppe Missori.",
  //   price: "Free",
  //   address: "Piazza Giuseppe Missori, 20122 Milan MI",
  //   rating: "4.4",
  //   label: "MONUMENTO",
  //   labelImage: require("../../assets/images/labelCross.png"),
  // },
  // {
  //   title: "Disco in forma di rosa del deserto",
  //   minutes: "10 min",
  //   image: require("@/assets/images/disco.jpg"),
  //   caption:
  //     "Modern sculpture located in piazza Meda, a symbol of contemporary art.",
  //   price: "Free",
  //   address: "Piazza Meda, 20121 Milan MI",
  //   rating: "4.5",
  //   label: "ATTRAZIONI",
  //   labelImage: require("../../assets/images/arte.png"),
  // },
  // {
  //   title: "Metro Cordusio",
  //   minutes: "6 min",
  //   image: require("@/assets/images/cordusio.jpg"),
  //   caption:
  //     "Junction of the red metro line, a central point for exploring the heart of Milan.",
  //   price: "€2.20",
  //   address: "Piazza Cordusio, 20123 Milan MI",
  //   rating: "4.3",
  //   label: "TRASPORTI",
  //   labelImage: require("../../assets/images/labelCross.png"),
  // },

  {
    title: "Museo del Novecento",
    image: require("@/assets/images/novecento.jpg"),
    caption: "Museum of Modern and Contemporary Art",
    price: "€5-€10",
    address: "Marconi Street, 1, 20122 Milano MI",
    rating: "4.6",
    label: "MUSEO",
    labelImage: require("../../assets/images/labelMuseum.png"),
  },
  {
    title: "Leonardo3",
    minutes: "5 min",
    image: require("@/assets/images/leonardo3.jpg"),
    caption:
      "Interactive museum and exhibition dedicated to Leonardo da Vinci's inventions",
    price: "€12",
    address: "Piazza della Scala, 20121 Milano MI",
    rating: "4.7",
    label: "MUSEO",
    labelImage: require("../../assets/images/labelMuseum.png"),
  },

  {
    title: "Monumento to Cesare Beccaria",
    minutes: "5 min",
    image: require("@/assets/images/beccaria.jpg"),
    caption:
      "Monument dedicated to the famous Italian criminologist and philosopher",
    price: "Free",
    address: "Piazza Beccaria, 20122 Milano MI",
    rating: "4.3",
    label: "MONUMENTO",
    labelImage: require("../../assets/images/labelMuseum.png"),
  },
  {
    title: "Sant Ambroeus Milano",
    minutes: "6 min",
    image: require("@/assets/images/ambrogio.jpg"),
    caption:
      "Historic café and pastry shop founded in 1936, famous for its pastries and coffee",
    price: "€€",
    address: "Corso Giacomo Matteotti, 7, 20121 Milano MI",
    rating: "4.6",
    label: "RISTORANTE",
    labelImage: require("../../assets/images/labelMuseum.png"),
  },
  {
    title: "Piazza San Babila",
    minutes: "4 min",
    image: require("@/assets/images/babila.jpg"),
    caption:
      "Historic square in the center of Milan with the San Babila Church",
    price: "Free",
    address: "Piazza San Babila, 20122 Milano MI",
    rating: "4.5",
    label: "ATTRAZIONI",
    labelImage: require("../../assets/images/labelMuseum.png"),
  },
];

export default tourStopsData;
